image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install && abtnode init -f --mode debug --no-https
    command: abtnode start && BLOCKLET_START_TIMEOUT=120 blocklet dev
ports:
  - port: 8080
    onOpen: ignore
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
